service: using-serverless-reasonml

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-reasonml

functions:
  hello:
    handler: src/handler.hello
    events:
      - http: POST hello
